# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

fastlane_version "2.60.0"

default_platform :ios

platform :ios do
  desc "Just build"
  lane :example_build do
    gym(
      project: "F82017.xcodeproj",
      scheme: "F82017",
      configuration: "Release",
      output_directory: "build",
      export_method: "development",
      output_name: "internal",
      xcargs: "-allowProvisioningUpdates"
    )
  end
end
